tdtt/Models/Topic/TopicStModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace web_project.Models.Topic
{
    public class TopicStModel
    {
        [Column(TypeName = "ntext")]
        public string Name { get; set; }

        [Column(TypeName = "ntext")]
        public string NameSt { get; set; }

        [StringLength(12)]
        public string IdSV { get; set; }

        [StringLength(30)]
        public string Email { get; set; }

        [StringLength(10)]
        public string IdTy { get; set; }


        [StringLength(10)]
        public string IdP { get; set; }

        [Column(TypeName = "date")]
        public DateTime? DateSt { get; set; }

        public int? Times { get; set; }
    }
}

tdtt/Controllers/TopicController.cs
using DataContext.DataMethod;
using DataContext.DataTable;
using DataContext.ViewModel;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using tdtt.Models.Login;

namespace tdtt.Controllers
{
    public class TopicController : BaseController
    {
        // GET: Topic
        public Information Information()
        {
            LoginSession user = (LoginSession)Session["User"];
            var info = new AccountSQL().GetInformation(user.UserName);
            return info;
        }
        public ActionResult MyTopic(string i = null, string ii = null, string date1 = null, string date2 = null)
        {

            ViewBag.Type = new PointSQL().GetTypes();
            ViewBag.Point = new PointSQL().GetPoints(i);
            string id = Information().IdLe;
            var model = new TopicLeSQL().GetTopicOfLectures(id);
            return View(model);
        }

        // GET: Topic/Details/5
        public ActionResult Details(string id)
        {
            var model = new TopicLeSQL().findTopic(id);
            ViewBag.Progress = new TopicLeSQL().getProcessbyId(model.IdTp);
            return PartialView(model);
        }
        public FileResult Download(string id, string filename)
        {
            var FileVirtualPath = "~/FileFolder/De-tai/" + id + "/" + filename;
            return File(FileVirtualPath, "application/force-download", Path.GetFileName(FileVirtualPath));
        }

        // GET: Topic/Create
        public ActionResult SignUpTopic(bool Issucess = false)
        {
            ViewBag.issucess = Issucess;
            return View();
        }

        // POST: Topic/Create
        [HttpPost]
        public ActionResult SignUp(TopicmdLe topic)
        {
            if (ModelState.IsValid)
            {
                string i = new TopicLeSQL().getLastId(topic.IdP).ToString();
                string ii = "LECT-" + topic.IdP + "000000";
                string id = ii.Substring(0, ii.Length - i.Length) + i;
                bool res = new TopicLeSQL().create(topic, id, Information().IdLe);
                if (true == res)
                {
                    return RedirectToAction("SignUpTopic", new { Issucess = true });
                }
                else
                {
                    ModelState.AddModelError("", "Đăng ký không thành công. Thử lại !!!");

                }
            }
            return RedirectToAction("SignupTopic", new { Issucess = false });
        }

        // GET: Topic/Edit/5
        public ActionResult Edit(string id)
        {
            var model = new TopicLeSQL().getTopic(id);
            ViewBag.Point = new PointSQL().GetPoints(null);
            return View(model);
        }

        // POST: Topic/Edit/5
        [HttpPost]
        public ActionResult Edit(TopicOfLecture topic)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Topic/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Topic/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
        [HttpGet]
        public ActionResult CreateProg(string id)
        {
            ViewBag.Status = new List<SelectListItem>{
                             new SelectListItem { Value = "Báo Cáo Lần 1" , Text = "Báo Cáo Lần 1" },
                             new SelectListItem { Value = "Báo Cáo Lần 2" , Text = "Báo Cáo Lần 2" },
                             new SelectListItem { Value = "Báo Cáo Lần 3" , Text = "Báo Cáo Lần 3" },
                             new SelectListItem { Value = "Báo Cáo Lần 4" , Text = "Báo Cáo Lần 4" },
                             new SelectListItem { Value = "Báo Cáo Lần 5" , Text = "Báo Cáo Lần 5" },
                             new SelectListItem { Value = "Báo Cáo Lần 6" , Text = "Báo Cáo Lần 6" },
                             new SelectListItem { Value = "Báo Cáo Lần 7" , Text = "Báo Cáo Lần 7" },
                             new SelectListItem { Value = "Báo Cáo Lần 8" , Text = "Báo Cáo Lần 8" },
                             new SelectListItem { Value = "Báo Cáo Lần 9" , Text = "Báo Cáo Lần 9" },
                             new SelectListItem { Value = "Báo Hoàn Thành" , Text = "Báo Cáo Hoàn Thành" }
                };

            ViewBag.id = id;
            return View();
        }
        [HttpPost]
        public ActionResult CreateProg(string id,ProgressLe progress, HttpPostedFileBase fileName)
        {
            progress.IdTp = id;
            if(fileName!=null&& fileName.ContentLength>0)
            {
                string filename = System.IO.Path.GetFileName(fileName.FileName);
                progress.FileName = filename.ToString();
                string url = Server.MapPath("~/FileFolder/De-tai/" + progress.IdTp +"/"+ filename);
                fileName.SaveAs(url);
                
                
            }
            bool res = new TopicLeSQL().UpProg(progress);
            if (true == res)
            {
                return RedirectToAction("mytopic");
            }
            else
                ModelState.AddModelError("", "Thất bại, thử lại");
            return RedirectToAction("CreateProg");
            
        }
        public ActionResult partialViewFile(string path)

        {
            return PartialView();
        }
    }
}

tdtt/Views/Topic/CreateProg.cshtml
@model DataContext.DataTable.ProgressLe

@{
    ViewBag.Title = "CreateProg";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>CreateProg</h2>

@using (Html.BeginForm("CreateProg","topic",FormMethod.Post, new { enctype ="multipart/form-data"}))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>ProgressLe</h4>
        <hr />

        <div class="form-group">
            <label class="control-label col-md-2"> Ngày thực hiện </label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control", @type = "date" } })
                @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2"> Quá trình </label>
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Status,null, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2"> File </label>
            <div class="col-md-10">
               <input  class="form-control" type="file" id="fileName" name="fileName"/>
                @Html.ValidationMessageFor(model => model.FileName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Mytopic")
</div>
<script type="text/javascript">
        document.getElementById("Date").valueAsDate = new Date();
    var date = moment().fomat('YYYY-MM-DD');
    document.getElementById("DateSt").value = date;</script>

tdtt/Views/Topic/Details.cshtml
@model DataContext.ViewModel.detailTopic

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var date = (DateTime)Model.DateSt;
    int stt = (int)Model.Status;
    var list = (List<DataContext.DataTable.ProgressLe>)ViewBag.Progress;
}

<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Chi tiết đề tài @Model.Name</h6>
    </div>
    <div class="card-body" style=" margin-left:15px">
        <div class="">
            <div id="dataTable_wrapper" class="dataTables_wrapper dt-bootstrap4">
                <div class="row">
                    <div>
                        <dl class="dl-horizontal">

                            <dd>
                                <label>Mã Nhiệm Vụ: </label><br />@Html.DisplayFor(model => model.IdTp)
                            </dd>

                            <dd>
                                <label>Tên Nhiệm Vụ: </label><br /> @Html.DisplayFor(model => model.Name)
                            </dd>

                            <dd>
                                <label>Loại Nhiệm Vụ :</label><br /> @Html.DisplayFor(model => model.name)
                            </dd>

                            <dd>
                                <label>Mục Tiêu : </label><br /> @Html.DisplayFor(model => model.Target)
                            </dd>

                            <dd>
                                <label>Nội Dung: </label><br />@Html.DisplayFor(model => model.Content)
                            </dd>

                            <dd>

                                <label>Ngày Thực Hiện: </label><br /> @date.ToShortDateString()
                            </dd>

                            <dd>
                                <label>Số Tháng Thực Hiện: </label><br />@Html.DisplayFor(model => model.Times)
                            </dd>

                            <dd>
                                <label>Kinh Phí: </label><br />  @string.Format("{0:#,0}", Model.Expense) VND

                            </dd>
                            <dd>
                                <label>Xét Duyệt: </label>
                                @if (stt == 2)
                                {
                                    <p>Đang chờ</p>
                                }
                                else if (stt == 1)
                                {
                                    <p>Chấp Thuận</p>

                                }
                                else
                                { <p>Không Chấp Thuận</p>}

                            </dd>

                        </dl>
                        <div class="alert alert-success" role="alert">
                            <strong>Quá Trình Thực Hiện</strong>
                            @foreach (var item in list)
                            {
                        <div>
                            @item.Status  @item.Date @item.FileName  <a href="@Url.Action("Download","Topic", new {id=item.IdTp, filename= item.FileName})"> tải xuống</a>
                            <button type="button" style=" background:none;border:none;color:blue" class="btn btn-block">xem trước</button>
                            <div class="modal fade" id="myModal" role="dialog" data-url='@Url.Action("partialViewFile","topic")'></div>

                            </div>
                            }
                        </div>
                    </div>
                    <p>
                        @if (stt == 2)
                        {
                            @Html.ActionLink("Edit", "Edit", new { id = Model.IdTp })
                        }
                        @if (stt == 1)
                        {
                            @Html.ActionLink("Gia Hạn", "Edit", new { /* id = Model.PrimaryKey */ })
                            <small>||</small>
                            @Html.ActionLink("Hủy Bỏ", "Edit", new { /* id = Model.PrimaryKey */ })
                        }

                        || @Html.ActionLink("Quay lại danh sách", "mytopic")
                    </p>

                </div>

            </div>
        </div>
    </div>
</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        $('.myModal').click(function () {
            var url = $('#myModal').data('url');
            $.get(url, function (data) {
                $("#myModal").html(data);
                $("#myModal").modal('show')
            })
        })
    })
</script>

tdtt/Views/Topic/Edit.cshtml
@model DataContext.DataTable.TopicOfLecture

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>TopicOfLecture</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.IdTp)

        <div class="form-group">
            <label class = "control-label col-md-2">Tên Đề Tài</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Mục Tiêu</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Target, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Target, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Nội Dung Thực Hiện</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Content, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            <label class="control-label col-md-2">Loại Nhiệm Vụ</label>
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.IdP, new SelectList(ViewBag.Point, "IdP", "NameP"), null, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IdP, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Ngày Bắt Đầu</label>
            <div class="col-md-10">
                <input type="date" value="@Model.DateSt.ToString("yyyy/MM/dd")" id="DateSt"/>
                @Html.ValidationMessageFor(model => model.DateSt, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Số Tháng Thực Hiên</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Times, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Times, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Kinh Phí</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Expense, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Expense, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>
<script src="~/Scripts/js/date.js"></script>

tdtt/Views/Topic/MyTopic.cshtml
@model IEnumerable<DataContext.ViewModel.TopicLecuter>

@{
    ViewBag.Title = "my topic";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div style="margin:1px 1px 1px 1px; border:1px solid blue;">
    @using (Html.BeginForm())
    {
        <div class="form-group" style="margin-top:10px">
            <label style="width:80px"> Từ ngày</label>
            <input type="date" value="01/01/2001" />
            <label style="width:80px;margin-left:60px">Đến ngày</label>
            <input type="date" value="@DateTime.Now" />
        </div>
        <hr />
        <div class="form-group">
            <label style="width:80px"> Lĩnh Vực</label>
            <select style="width:auto">
                <option value>Chọn Lĩnh Vực</option>
                @foreach (var item in (List<DataContext.DataTable.Type>)ViewBag.Type)
                {
                    <option value="@item.IdTy">@item.Name</option>
                }
            </select>

            <label style="width: 125px; margin-left: 60px; margin-bottom:10px"> Loại Nhiệm Vụ</label>
            <select>
                <option value>Chọn Nhiệm Vụ</option>
                @foreach (var item in (List<DataContext.DataTable.PointTable>)ViewBag.Point)
                {
                    <option value="@item.IdP">@item.NameP</option>
                }
            </select>
        </div>
        <hr />
        <div class=" form-group" style="margin-bottom:10px">
            <input type="submit" value="Lọc" class="btn btn-facebook" style="width:150px;margin-left:60%" />
        </div>
    }

</div>

<hr />
<small>
    <table class="table" id="tbtopic">
        <tr style=" font-size:small">
            <th>
            </th>
            <th>
                Tên Nhiện Vụ
            </th>
            <th>
                Thể Loại
            </th>
            <th>
                Ngày Thực Hiện
            </th>
            <th>
                Thời Gian
            </th>
            <th>
                Chi Phí
            </th>
            <th>
                Trạng Thái
            </th>
            <th>
                Kết Quả
            </th>
            <th> <button onclick="ExportToExcel(tbtopic)">>>> Excel</button></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @item.IdTp
                </td>
                <td>
                    <a href="/de-tai/@item.IdTp"> @item.Name</a>

                </td>
                <td>
                    @item.NameP
                </td>
                <td>
                    @item.DateSt.ToShortDateString()
                </td>
                <td>
                    @item.Times <small>(Tháng)</small>
                </td>
                <td>
                    @string.Format("{0:#,0}", item.Expense)
                </td>
                @if (item.Status == 2)
                {
                    <td>
                        Chưa Duyệt
                    </td>
                }
                else if (item.Status == 1)
                {
                    <td>
                        Đã Duyệt
                    </td>
                }
                else if (item.Status
                    == 0)
                {
                    <td>
                        Bị Hủy
                    </td>
                }
                else
                {
                    <td>
                        !!!!!!
                    </td>
                }
                @if (item.Process != null)
                {
                    <td>
                        @item.Process
                    </td>
                }
                else
                {
                    <td> </td>
                }

                <td>
                    <a href="@Url.Action("createprog","topic",new { id= item.IdTp})">Cập Nhật</a>
                </td>
            </tr>
        }

    </table>
</small>

<script type="text/javascript">
    function ExportToExcel(tblId) {
        var htmltable = document.getElementById(tblId);
        var html = htmltable.outerHTML;
        window.open('data:application/vnd.ms-excel,' + encodeURIComponent(html));
    }
</script>
<script type="text/javascript">
    $(document).ready(function () {
    })
</script>

tdtt/Views/Topic/SignUpTopic.cshtml
@model DataContext.ViewModel.TopicmdLe

@{
    ViewBag.Title = "SignUpTopic";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@if (ViewBag.issucess)
{
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
        <strong>Đăng ký thành công</strong> You should check in on some of those fields below.
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>

}

@using (Html.BeginForm("SignUp", "topic", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal" style="align-items:center">
        <h4>Đăng Ký Đề tài</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <label class="control-label col-md-2">Tên Nhiệm Vụ</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Mục Tiêu</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Target, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Target, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Nội Dung Thực Hiện</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Content, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Lĩnh Vực</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.IdLe, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IdLe, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Loại Nhiệm Vụ</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.IdP, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IdP, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Ngày Bắt Đầu</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateSt, new { htmlAttributes = new { @class = "form-control", @type = "date" } })
                @Html.ValidationMessageFor(model => model.DateSt, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Số Tháng Thực Hiên</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Times, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Times, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Chi phí</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Expense, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Expense, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Đăng Ký" class="btn btn-facebook" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>
<script type="text/javascript">
    $(function () {

        $("form").submit(function (e) {
            e.preventDefault();
            var f = $(this);
            $.post(f.attr("action"), f.serialize(), function (res) {
                if (res.Status === "success") {
                    alert(res.Message);
                    window.location.href = "/topic/mytopic";
                }
            });
        });

    });
   
</script>
<script type="text/javascript">
    document.getElementById("DateSt").valueAsDate = new Date();
    var date = moment().fomat('YYYY-MM-DD');
    document.getElementById("DateSt").value = date;
</script>

tdtt/Views/Topic/partialViewFile.cshtml
<div class=" row">
    <div class=" col-sm-4"></div>
    <div class=" modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button class="close" type="button" data-dismiss="modal" aria-hidden="true">&times; </button>
                <h4></h4>
            </div>
            <div class="modal-body">
                ......
            </div>
            <div class=" modal-footer">
                <button class="btn btn-primary" id="btnOk" onclick="">OK</button>
                <button class="btn btn-default" data-dismiss="modal" id="btnCancle">Cancle</button>
            </div>
        </div>
    </div>
</div>